---
title: "Final Project Proposal: *Weather-Disease Correlation Explorer*"
author: "Team: Juanyu Zhang, Yunyi Ru, Yuzi Zhang"
date: "2024-11-15"
bibliography: 
 - my-refs.bib
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

*Using quarto, write up a project proposal andsubmit the PDF. The final project proposal should include the following information*:

**1. The title of your project and the team members names**

(As shown above)

**2. You should describe a research or data analysis question and explain its importance**

We want to investigate the correlation between climate and weather-related conditions and outbreaks of two respiratory viruses, influenza and respiratory syncytial virus (RSV).

Influenza is an RNA virus from the *Orthomyxoviridae* family that frequently mutates, causing seasonal epidemics, while RSV is an RNA virus from the *Paramyxoviridae* family that primarily affects young children and the elderly, often leading to severe lower respiratory infections. 

Both viruses pose significant public health challenges due to their widespread transmission and potential for severe disease.

**3. You should summarize work that already exists (if it does)**

Climate and weather conditions can influence the activity and spread of both viruses. Studies have suggested that factors like cold temperatures, low indoor humidity, limited sunlight, and rapid weather changes may increase the risk of outbreaks [@carter-templeton_associations_2022] [@chong_association_2022] [@fdez-arroyabe_effects_2021] [@linssen_association_2021].

**4. You should outline the work you plan to do**

In this project, we plan to integrate weather data and disease incidence data together to perform correlation and regression analysis, and to build an interactive dashboard showing those relationships. If possible, we also want to build a machine learning model to predict potential disease outbreaks based on weather data. 

**5. You should demonstrate you have access to the data, describe the data, and propose how you will collect the data**

Weather data will be collected through the [National Weather Service (NWS) API](https://www.weather.gov/documentation/services-web-api) [@us_department_of_commerce_api_nodate] or [Openweather API](https://openweathermap.org/api) [@noauthor_weather_nodate].

Disease incidence data will be collected from the [CDC National Notifiable Diseases Surveillance System (NNDSS)](https://www.cdc.gov/nndss/data-statistics/infectious-tables/index.html) [@noauthor_notifiable_2023].

All of the data sources mentioned above are open to the public and downloadable from the website.

**6. You should describe the programming paradigms you plan to use and why it makes sense to combine them for your project**

We plan to use a combination of functional programming and object-oriented programming (OOP) for this project. This paradigm is well-suited for our project because it emphasizes immutability and reusable functions, which align with our need to process data repeatedly across different subsets and analyses. OOP will be used for structuring the machine learning model and data pipeline.

**7. You should describe any packages and/or software you plan to use**

Data Collection :

- `httr` and `jsonlite`: For fetching weather data via APIs.

Data Analysis:

-   `dplyr` and `tidyr`: For advanced data manipulation.
-   `stats` and `lmtest`: For performing correlation and regression analyses.
-   `lubridate`: For handling temporal data efficiently.

Visualization:

-   `ggplot2`: For static and interactive visualizations of weather and disease patterns.

**8. You should briefly describe the data analytic product you plan to build.**

The final product will be an interactive dashboard, which will include:

-   Weather-Disease Correlation Explorer: Users can select specific weather variables (e.g., temperature, humidity) and see their correlation with disease incidence over time.

-   Seasonal Trend Analysis: Visualizations of trends for specific locations, highlighting high-risk periods.

-   Customizable Reports: Users can generate downloadable summaries of findings in PDF or HTML format.

**9. You should describe a tentative timeline for the proposal**

-   Nov. 18 - Dec. 5: Collect and clean data
-   Dec. 5 - Dec. 10: Visualize data

**10. You should describe how the tasks will be split amongst the team members**

-   Data Collection: Yuzi
-   Data Analysis and Visualization: Yunyi and Juanyu
